### ISSUE TITLE
`cargo test` failing two tests on macOS

### ISSUE THREAD

**Issue by dylanmc** [neogenie/fastnum#2]
`cargo test` produces the same results on both my x86 mac pro running macOS 12.7.6 and my M1 macbook pro running macOS 15.2:

```
running 165 tests
test src/../doc/LIB.md - (line 115) - compile fail ... ok
test src/../doc/LIB.md - (line 122) - compile fail ... ok
test src/../doc/LIB.md - (line 1367) ... FAILED
test src/../doc/LIB.md - (line 1344) ... FAILED
test src/../doc/LIB.md - (line 602) ... ok
... the rest succeed
```

Perhaps the cause: there seems to be a missing dependency on `serde`, as reported later:

```
...
failures:

---- src/../doc/LIB.md - (line 1367) stdout ----
error[E0432]: unresolved import `serde`
 --> src/../doc/LIB.md:1370:5
  |
6 | use serde::*;
  |     ^^^^^ use of undeclared crate or module `serde`

error: cannot find derive macro `Serialize` in this scope
 --> src/../doc/LIB.md:1373:17
  |
9 | #[derive(Debug, Serialize, Deserialize)]
```

**Comment by neogenie** [comment]
Try `cargo test --all-features` just now. And I'll fix it asap.

**Comment by dylanmc** [comment]
Tail end of output of `cargo test --all-features`
```
failures:

---- decimal::extras::utoipa::dec512::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::dec512::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:5:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"D512": Object {"description": String("Fixed-size signed 512-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D512"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D512")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"D512": Object {"description": String("Fixed-size signed 512-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D512"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D512")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}

---- decimal::extras::utoipa::udec256::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::udec256::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:8:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD256")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD256": Object {"description": String("Fixed-size unsigned 256-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD256"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD256")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD256": Object {"description": String("Fixed-size unsigned 256-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD256"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}

---- decimal::extras::utoipa::dec256::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::dec256::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:4:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"D256": Object {"description": String("Fixed-size signed 256-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D256"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D256")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"D256": Object {"description": String("Fixed-size signed 256-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D256"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D256")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}

---- decimal::extras::utoipa::udec512::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::udec512::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:9:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD512")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD512": Object {"description": String("Fixed-size unsigned 512-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD512"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD512")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD512": Object {"description": String("Fixed-size unsigned 512-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD512"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}

---- decimal::extras::utoipa::udec128::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::udec128::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:7:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD128")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD128": Object {"description": String("Fixed-size unsigned 128-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD128"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/UD128")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}, "UD128": Object {"description": String("Fixed-size unsigned 128-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("1.5")], "format": String("number"), "title": String("UD128"), "type": String("string")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}

---- decimal::extras::utoipa::dec128::test_utoipa_api_doc stdout ----
thread 'decimal::extras::utoipa::dec128::test_utoipa_api_doc' panicked at tests/decimal/extras/utoipa.rs:3:1:
assertion `left == right` failed
  left: Object {"components": Object {"schemas": Object {"D128": Object {"description": String("Fixed-size signed 128-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D128"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D128")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"identifier": String("MIT OR Apache-2.0"), "name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
 right: Object {"components": Object {"schemas": Object {"D128": Object {"description": String("Fixed-size signed 128-bits decimal number"), "examples": Array [String("0.0"), String("1.23"), String("-1.5")], "format": String("number"), "title": String("D128"), "type": String("string")}, "Pet": Object {"properties": Object {"age": Object {"$ref": String("#/components/schemas/D128")}, "id": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}, "name": Object {"type": String("string")}}, "required": Array [String("id"), String("name"), String("age")], "type": String("object")}}}, "info": Object {"contact": Object {"name": String("Neo")}, "description": String("Fast decimal numbers library"), "license": Object {"name": String("MIT OR Apache-2.0")}, "title": String("fastnum"), "version": String("0.1.4")}, "openapi": String("3.1.0"), "paths": Object {"/pets/{id}": Object {"get": Object {"operationId": String("get_pet_by_id"), "parameters": Array [Object {"description": String("Pet database id to get Pet for"), "in": String("path"), "name": String("id"), "required": Bool(true), "schema": Object {"format": String("int64"), "minimum": Number(0), "type": String("integer")}}], "responses": Object {"200": Object {"content": Object {"application/json": Object {"schema": Object {"$ref": String("#/components/schemas/Pet")}}}, "description": String("Pet found successfully")}, "404": Object {"description": String("Pet was not found")}}, "tags": Array []}}}}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    decimal::extras::utoipa::dec128::test_utoipa_api_doc
    decimal::extras::utoipa::dec256::test_utoipa_api_doc
    decimal::extras::utoipa::dec512::test_utoipa_api_doc
    decimal::extras::utoipa::udec128::test_utoipa_api_doc
    decimal::extras::utoipa::udec256::test_utoipa_api_doc
    decimal::extras::utoipa::udec512::test_utoipa_api_doc

test result: FAILED. 9078 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.54s

error: test failed, to rerun pass `--test tests`
```

Same result (different elapsed time) on both systems.

**Comment by neogenie** [comment]
Uups... 
Try `v0.1.5` please...

**Comment by dylanmc** [comment]
>  Try v0.1.5 please...

Both platforms report:

```
...
test src/int/macros.rs - int::macros::u8192 (line 9) ... ok

test result: ok. 167 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 20.99s
```

Closing this issue - nice!
